### ISSUE TITLE
SCSS Support?

### ISSUE THREAD

**Issue by CanKattwinkel** [clbond/angular-ssr#14]
Hello, 

what is the current state for SCSS?

I've found this [commit](https://github.com/clbond/angular-ssr/commit/fa012ca934d05c98be83da0890935c1facd53bc6) but I'm receiving many errors in an existing project. I think this is caused by wrong interpreted scss imports inside of .scss files.

**Example:**
```
  __zone_symbol__stack: 'Error: Compilation failed. Resource file not found: XXXX/www/src/styling/mixins/background-gardient\n    at ResourceResolver.ModuleResolutionHostAdapter.readResource 
```

Import in someFile.scss (usage)
`@import "mixins/background-gardient";`

Real Filename: 
`_background-gardient.scss`

**Comment by leo6104** [comment]
In my case, i can reolsve the problem with specifying the extension 'scss' 

ex)
@import "mixins/background-gardient.scss";

**Comment by clbond** [comment]
Hmmm. Thank you for the note both @CanKattwinkel and @leo6104. I'll try to fix the scss import behaviour

**Comment by clbond** [comment]
Hi @CanKattwinkel. This should be resolved in the latest version, `0.1.40`, because it has proper webpack integration. Would you mind verifying that your SCSS issue is resolved so that I can close this issue?

**Comment by leo6104** [comment]
@clbond I verify this issue with my project. It now works even if not specify the scss extension.

**Comment by clbond** [comment]
Awesome! Thank you @leo6104. Closing
