### ISSUE TITLE
Material Support and ValidityState API

### ISSUE THREAD

**Issue by smithad15** [clbond/angular-ssr#19]
I'm having an issue when pre-rendering an angular material beta 3 project using `ng-render`. It is failing on this line: https://github.com/angular/material2/blob/2.0.0-beta.3/src/lib/input/input-container.ts#L243 as `validity` is `undefined` on the native element that's being returned. If Domino doesn't support the [ValidityState web API](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState), can we add a polyfill for it?

**Comment by clbond** [comment]
Yes. This has been resolved and `md-input`s work now.
