### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by gdi2290** [clbond/angular-ssr#2]
Can I jump on call with you to for a code walkthrough?

**Comment by clbond** [comment]
Sure. Tomorrow afternoon? What timezone are you in?

**Comment by gdi2290** [comment]
I'm EST what email do you use for google hangouts?

**Comment by clbond** [comment]
chris.bond@rangle.io

**Comment by clbond** [comment]
I am available now if you want to chat

**Comment by MarkPieszak** [comment]
@gdi2290 Yo you guys talk already, would love to jump in if possible ?
Been looking at this as well, looks pretty damn amazing @clbond

**Comment by clbond** [comment]
Hey @MarkPieszak. If you can make your code available to me, I would be happy to get it working with angular-ssr. That might be more efficient than going back and forth on these issues

**Comment by gdi2290** [comment]
kool I invited and created a group
