### ISSUE TITLE
ng-render failing with out of memory error

### ISSUE THREAD

**Issue by buu700** [clbond/angular-ssr#26]
Tested with angular-ssr 0.1.88, Angular 4.1, TypeScript 2.3.1, and Node 7.9.0 on Debian Sid in a Docker container with 2 GB RAM allocated.

[My project](https://github.com/cyph/cyph) doesn't use the Angular CLI, but otherwise it should be a typical enough Angular project that I wouldn't expect any issues working with angular-ssr (routes configured with @angular/router, AOT with webpack + @ngtools/webpack, UI built with @angular/material and @angular/flex-layout, occasional use of web-dependent libs like JQuery).

The command that triggers this result is: `ng-render --template /home/gibson/.build/cyph.com/index.html --module cyph.com/app.module.ts --symbol AppModule --project . --webpack cyph.com/main.webpack.js --output /home/gibson/.build/cyph.com`.

Based on the stack trace below, it looks like `patchModuleSearch` in render.ts is the culprit. The path of our node_modules in this Docker image is `/node_modules`; maybe it's just handling that incorrectly?

```
<--- Last few GCs --->

[6924:0x55abce62c7e0]   156609 ms: Mark-sweep 1242.6 (1300.6) -> 1242.3 (1301.1) MB, 333.3 / 0.0 ms  allocation failure GC in old space requested
[6924:0x55abce62c7e0]   156942 ms: Mark-sweep 1242.3 (1301.1) -> 1242.2 (1270.1) MB, 327.0 / 0.0 ms  last resort
[6924:0x55abce62c7e0]   157302 ms: Mark-sweep 1242.2 (1270.1) -> 1242.2 (1269.6) MB, 359.2 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x32b43d3a66a1 <JS Object>
    2: patchModuleSearch(aka patchModuleSearch) [/node_modules/angular-ssr/build/bin/render.js:~87] [pc=0x1964983cafee](this=0xc74c2602311 <undefined>)
    3: arguments adaptor frame: 2->0
    4: /* anonymous */ [/node_modules/angular-ssr/build/bin/render.js:44] [pc=0x196497b56891](this=0x2a78aeb67599 <an Object with map 0x14703482cd61>,exports=0x2a78aeb67599 <an Object with map 0x14703482cd61>...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x55abcc95b05e [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0x55abcc41459b [node]
 7: 0x55abcc0b914c [node]
 8: v8::internal::Runtime_ArrayPush(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 9: 0x196497a0ed46
```

**Comment by buu700** [comment]
Looks like the problem is that `PathImpl.parent()` doesn't work when the path is "."; it just returns the same path, causing `patchModuleSearch` to loop infinitely.

Setting `--project` to `${PWD}` instead of `.` in my script resolved this error.

**Comment by clbond** [comment]
Thank you! I will fix `PathImpl`
