### ISSUE TITLE
Current document does not have a doctype

### ISSUE THREAD

**Issue by GarryBrown** [clbond/angular-ssr#32]
Hi! I'm use cli from example dir and it's amazing! Thx! 
But Angular Material show warning logs and some components behavior  breaks because of html after build does not have a doctype.
In browser : "Current document does not have a doctype. This may cause some Angular Material components not to behave as expected."  

May you add to build generator <doctype> in html document?

**Comment by clbond** [comment]
I think that warning is spurious, but I will take a look. Thank you

**Comment by GarryBrown** [comment]
For example, size of modals and labels of inputs breaks in my case.  But when i add doctype manually it's works and warnings hides.

**Comment by clbond** [comment]
How do you manually add the doctype? To `src/index.html` or `dist/index.html`?

**Comment by GarryBrown** [comment]
To dist/index.html
If we run just ng build doctype exist in dist/index.html, but how i understand ather rendering(npm run build) doctype removing.

**Comment by clbond** [comment]
OK, this is resolved in version `0.1.107`. It always ensures there is a `<!doctype html>` in the output now. Thank you for your bug report!
