### ISSUE TITLE
Unable to load lazy load module 

### ISSUE THREAD

**Issue by vlodkow** [clbond/angular-ssr#40]
When I try to load url from lazy load module server return right response, but when client code loaded, after few seconds content disappear (no errors in console).

When I remove lazy loading or reload page without cache all working fine.

Tested on browsers: Safari (v 10.1.1) and Chrome (v 58.0.3029.81)

**Comment by vlodkow** [comment]
When I remove preboot from AppModule constructor all fixed.. preboot remove incorrect tag when call prebootClient().complete();

**Comment by clbond** [comment]
If it's getting the wrong tag ID you can specify it yourself using `builder.preboot({appRoot: 'my-tag-id'})`
