### ISSUE TITLE
Angular i18n support

### ISSUE THREAD

**Issue by smoke** [clbond/angular-ssr#43]
How can I pre-render project that uses couple of languages based on this guide https://angular.io/docs/ts/latest/cookbook/i18n.html and uses @angular/cli (non ejected).

I have tried a lot of things, but it seems the angular-ssr uses the source and starts the project, but there is no way I can point it to the proper translation files.
Am I missing something or this feature is not implemented? Is such feature considered for implementation any soon and would that be easily achievable?

**Comment by clbond** [comment]
`angular-ssr` doesn't really integrate with the i18n stuff (although if you define `LOCALE_ID` in your module, it will set `navigator.language` to that value). I would love to support this and if you wish to submit a PR, I would be thrilled to accept it. But honestly I am not sure it can be done in a way that works for every project. The `examples/demand-express` shows an example of how you can use translations with on-demand rendering but it doesn't use Angular's native i18n facilities.

**Comment by smoke** [comment]
Thanks for the answer.
I had actually tried implementing this, but my lack of knowledge on the angular-ssr and errors like https://github.com/clbond/angular-ssr/issues/47 have stopped me for now.

**Comment by clbond** [comment]
I posted a comment in #47 about how to solve your issue. Don't use `@ngtools/webpack` for `ng-render` builds.
