### ISSUE TITLE
TypeError: moduleFactory._injectorClass is not a constructor

### ISSUE THREAD

**Issue by cyr-x** [clbond/angular-ssr#46]
Bug:
I'm running into the same Error with my repo and even with your `demand-express` example. It always says:
`TypeError: moduleFactory._injectorClass is not a constructor`

The error is coming from `source/platform/platform.ts line 113`:
```TS
const createInjector = <M>(injector: Injector, moduleFactory: NgModuleFactory<M>): InstantiableModule<M> => new moduleFactory['_injectorClass'](injector);
```

The argument `moduleFactory` doesn't have the attribute `_injectorClass`, it looks like that during runtime:
```TS
NgModuleFactory_ {
  moduleType: [Function: RootModule],
  _bootstrapComponents: [ [Function: RootComponent] ],
  _ngModuleDefFactory: [Function]
}
```

I'm using your demand-express example.

Edit:

It's probably because of this commit https://github.com/angular/angular/commit/ce1d7c4a6e46de00fc0c4aae0d046de34d6a8395, they removed the _injectorClass attribute from NgModuleFactory

**Comment by clbond** [comment]
This has been resolved in the latest builds.
