### ISSUE TITLE
Example of data transfer from server to client

### ISSUE THREAD

**Issue by karthicksiva** [clbond/angular-ssr#48]
@clbond First of all, thanks for this great repo ! It's the first SSR solution which works as advertised. Great work 👍 

I am using on-demand SSR solution using Express. Its working great. I am trying to find a way to transfer some data from Express res.locals object to client through index.html, on page load. So, I can avoid an ajax call. 

Is there an example, I can refer, where this might be possible ? Any help is greatly appreciated

**Comment by clbond** [comment]
This is described in detail in the readme. You just call `ApplicationBuilder::stateReader` and give it your state reader class. Read this: https://github.com/clbond/angular-ssr#state-transfer-from-server-to-client
