### ISSUE TITLE
Styles mess

### ISSUE THREAD

**Issue by vlodkow** [clbond/angular-ssr#49]
All styles loaded 2 times in style attributes (one from server, another when app is loaded)

**Comment by clbond** [comment]
Use `--inline=false`

**Comment by rafinskipg** [comment]
@clbond  how do we add the option if we are using the "on demand" rendered with express?

**Comment by ktersius** [comment]
@clbond I would also be interested in this. 

I'm getting duplicated styles, another issue I'm experiencing is that host style attributes are being applied on the wrong elements as well. Still troubleshooting this issue.
