### ISSUE TITLE
element.innerText returning null

### ISSUE THREAD

**Issue by MarkPieszak** [clbond/angular-ssr#7]
Like we were talking about earlier, could be a domino issue not sure, just wanted to log in just incase.

```typescript
        var temp = document.createElement('div');
        temp.innerHTML = '<h1>Whatever</h1>';
        if( temp.innerText.length )
                                    ^ will break server here
```

**Comment by guzuomuse** [comment]
same scenario with jquery even use isBrowser() or not.

**Comment by clbond** [comment]
`innerText` is not recommended - can you use `textContent` instead?
