### ISSUE TITLE
Cannot set property 'title' of undefined at BrowserDomAdapter.setTitle

### ISSUE THREAD

**Issue by MarkPieszak** [clbond/angular-ssr#9]
Seems that we need to make sure we're patching the `Title` service correctly. Might need to look into if the Meta service is doing the same.

To repro:
`this.title.setTitle(' blow up the server :) ')`

```
BrowserDomAdapter.prototype.setTitle = function (doc, newTitle) { document.title = newTitle || ''; };
```

**Comment by clbond** [comment]
Hi @MarkPieszak, thank you for this report. This should be resolved in the latest version of the library. Would you mind verifying so I can close this ticket?
